# Generated by Django 5.2 on 2025-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accuracyresult",
            name="unique_accuracy_session_withdp_mitigator",
        ),
        migrations.RemoveConstraint(
            model_name="fairnessevaluationresult",
            name="unique_fairness_session_withdp_mitigator",
        ),
        migrations.RemoveConstraint(
            model_name="privacyevaluationresult",
            name="unique_privacy_session_withdp_mitigator",
        ),
        migrations.AddConstraint(
            model_name="accuracyresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_accuracy_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="fairnessevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_fairness_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="privacyevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_privacy_session_withdp_mitigator",
            ),
        ),
    ]
