# Generated by Django 4.2.19 on 2025-03-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reporthistory",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="webapp_sess_user_id_c58369_idx",
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="webapp_sess_epsilon_fc11b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="webapp_sess_user_id_6d9473_idx",
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="epsilon",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="test_acc_g0_minus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="test_acc_g0_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="test_acc_g1_minus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="test_acc_g1_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="total_train_acc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="train_acc_g0_minus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="train_acc_g0_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="train_acc_g1_minus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accuracyresult",
            name="train_acc_g1_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="bal_acc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="disp_imp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="epsilon",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="eq_opp_diff",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="stat_par_diff",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairnessevaluationresult",
            name="theil_ind",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacyevaluationresult",
            name="epsilon",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privacyevaluationresult",
            name="privacy_risk_g0_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacyevaluationresult",
            name="privacy_risk_g1_minus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacyevaluationresult",
            name="privacy_risk_g1_plus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accuracyresult",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="fairnessevaluationresult",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="privacyevaluationresult",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="reporthistory",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddataset",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedmodel",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
        migrations.AddIndex(
            model_name="accuracyresult",
            index=models.Index(
                fields=["session", "epsilon"], name="webapp_accu_session_02128c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fairnessevaluationresult",
            index=models.Index(
                fields=["session", "epsilon"], name="webapp_fair_session_b8973c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyevaluationresult",
            index=models.Index(
                fields=["session", "epsilon"], name="webapp_priv_session_77d625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "epsilon"], name="webapp_sess_user_id_32296b_idx"
            ),
        ),
    ]
