# Generated by Django 5.1.1 on 2025-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_alter_reporthistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accuracyresult",
            name="with_dp",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
