# Generated by Django 5.1.1 on 2025-04-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_accuracyresult_with_dp"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accuracyresult",
            name="webapp_accu_session_02128c_idx",
        ),
        migrations.RemoveIndex(
            model_name="fairnessevaluationresult",
            name="webapp_fair_session_b8973c_idx",
        ),
        migrations.RemoveIndex(
            model_name="privacyevaluationresult",
            name="webapp_priv_session_77d625_idx",
        ),
        migrations.AlterField(
            model_name="accuracyresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="fairnessevaluationresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterField(
            model_name="privacyevaluationresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accuracyresult",
            unique_together={("session", "with_dp")},
        ),
        migrations.AlterUniqueTogether(
            name="fairnessevaluationresult",
            unique_together={("session", "with_dp")},
        ),
        migrations.AlterUniqueTogether(
            name="privacyevaluationresult",
            unique_together={("session", "with_dp")},
        ),
        migrations.AddIndex(
            model_name="accuracyresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp"],
                name="webapp_accu_session_7c6b53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fairnessevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp"],
                name="webapp_fair_session_fced8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="privacyevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp"],
                name="webapp_priv_session_440b88_idx",
            ),
        ),
    ]
