# Generated by Django 5.1.1 on 2025-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webapp",
            "0004_remove_accuracyresult_webapp_accu_session_02128c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accuracyresult",
            name="webapp_accu_session_7c6b53_idx",
        ),
        migrations.RemoveIndex(
            model_name="fairnessevaluationresult",
            name="webapp_fair_session_fced8b_idx",
        ),
        migrations.RemoveIndex(
            model_name="privacyevaluationresult",
            name="webapp_priv_session_440b88_idx",
        ),
        migrations.AlterUniqueTogether(
            name="accuracyresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="fairnessevaluationresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="privacyevaluationresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="privacyevaluationresult",
            name="mitigator",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="accuracyresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_accu_session_5d080c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fairnessevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_fair_session_eb000a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="privacyevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_priv_session_47ad84_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accuracyresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_accuracy_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="fairnessevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_fairness_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="privacyevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_privacy_session_withdp_mitigator",
            ),
        ),
    ]
