# Generated by Django 5.1.1 on 2025-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webapp",
            "0005_remove_accuracyresult_webapp_accu_session_7c6b53_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accuracyresult",
            name="unique_accuracy_session_withdp_mitigator",
        ),
        migrations.RemoveConstraint(
            model_name="fairnessevaluationresult",
            name="unique_fairness_session_withdp_mitigator",
        ),
        migrations.RemoveConstraint(
            model_name="privacyevaluationresult",
            name="unique_privacy_session_withdp_mitigator",
        ),
        migrations.AddConstraint(
            model_name="accuracyresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_accuracy_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="fairnessevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_fairness_session_withdp_mitigator",
            ),
        ),
        migrations.AddConstraint(
            model_name="privacyevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator", "epsilon"),
                name="unique_privacy_session_withdp_mitigator",
            ),
        ),
    ]
