# Generated by Django 4.2.20 on 2025-04-27 15:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("job_role", models.CharField(blank=True, max_length=255, null=True)),
                ("job_field", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="custom_user_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="custom_user_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dp_model_type", models.CharField(max_length=255)),
                ("dp_model_parameters", models.JSONField()),
                ("mitigators", models.CharField(max_length=255)),
                ("epsilon", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="models/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label_name", models.CharField(max_length=255)),
                ("pa_name", models.CharField(max_length=255)),
                ("fav_label", models.FloatField()),
                ("priv_attb", models.FloatField()),
                ("file", models.FileField(upload_to="datasets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("with_dp", models.BooleanField()),
                ("epsilon", models.FloatField()),
                ("mitigator", models.CharField(max_length=255)),
                ("privacy_risk_g0_minus", models.FloatField(blank=True, null=True)),
                ("privacy_risk_g0_plus", models.FloatField(blank=True, null=True)),
                ("privacy_risk_g1_minus", models.FloatField(blank=True, null=True)),
                ("privacy_risk_g1_plus", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FairnessEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("with_dp", models.BooleanField()),
                ("epsilon", models.FloatField()),
                ("mitigator", models.CharField(max_length=255)),
                ("bal_acc", models.FloatField(blank=True, null=True)),
                ("avg_odds_diff", models.FloatField(blank=True, null=True)),
                ("disp_imp", models.FloatField(blank=True, null=True)),
                ("stat_par_diff", models.FloatField(blank=True, null=True)),
                ("eq_opp_diff", models.FloatField(blank=True, null=True)),
                ("theil_ind", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccuracyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("with_dp", models.BooleanField()),
                ("epsilon", models.FloatField()),
                ("mitigator", models.CharField(max_length=255)),
                ("total_train_acc", models.FloatField(blank=True, null=True)),
                ("total_test_acc", models.FloatField(blank=True, null=True)),
                ("train_acc_g0_minus", models.FloatField(blank=True, null=True)),
                ("train_acc_g0_plus", models.FloatField(blank=True, null=True)),
                ("train_acc_g1_minus", models.FloatField(blank=True, null=True)),
                ("train_acc_g1_plus", models.FloatField(blank=True, null=True)),
                ("test_acc_g0_minus", models.FloatField(blank=True, null=True)),
                ("test_acc_g0_plus", models.FloatField(blank=True, null=True)),
                ("test_acc_g1_minus", models.FloatField(blank=True, null=True)),
                ("test_acc_g1_plus", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.session"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "epsilon"], name="webapp_sess_user_id_32296b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_priv_session_47ad84_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="privacyevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_privacy_session_withdp_mitigator",
            ),
        ),
        migrations.AddIndex(
            model_name="fairnessevaluationresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_fair_session_eb000a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fairnessevaluationresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_fairness_session_withdp_mitigator",
            ),
        ),
        migrations.AddIndex(
            model_name="accuracyresult",
            index=models.Index(
                fields=["session", "epsilon", "with_dp", "mitigator"],
                name="webapp_accu_session_5d080c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accuracyresult",
            constraint=models.UniqueConstraint(
                fields=("session", "with_dp", "mitigator"),
                name="unique_accuracy_session_withdp_mitigator",
            ),
        ),
    ]
